apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1
spec:
  containers:
    - name: pod1-container
      image: 957817/devnet:0.0.2
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-configmap


