kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devnet:0.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

