apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
    app: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
        - name: dep
          image: httpd:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

