apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devnet
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: devnet
  template: 
    metadata: 
      labels: 
        app: devnet
    spec: 
      containers: 
        - name: devnet
          image: 957817/devnet-app:v4
          ports:
            - containerPort: 9001
          env:
            - name: PORT
              value: "9001"
            - name: DB_HOST
              value: devnet-postgres:5432
            - name: DB_DATABASE
              value: devnet
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
          volumeMounts:
            - name: armazem
              mountPath: /app/armazem
      volumes:
        - name: armazem
          hostPath:
            path: /app/armazem
            type: DirectoryOrCreate

