apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devnet-app
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: devnet-app
  template: 
    metadata: 
      labels: 
        app: devnet-app
    spec: 
      containers: 
        - name: devnet
          image: 957817/devnet:latest
          ports:
            - containerPort: 9001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: password
          volumeMounts:
            - name: armazem
              mountPath: /app/armazem
      volumes:
        - name: armazem
          hostPath:
            path: /app/armazem
            type: DirectoryOrCreate

