apiVersion: v1
kind: Pod
metadata:
  name: devnet-pod1
  labels:
    app: devnet-pod1
spec:
  containers:
    - name: devnet-pod1
      image: eclipse-temurin:17.0.7_7-jdk-jammy
      ports:
        - containerPort: 3000
