version: '3.9'

services:
  db:
    image: postgres
    container_name: devnet_postgres
    restart: always
    environment:
      POSTGRESQL_DB: techchallenge
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - devnet-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  devnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devnet
    working_dir: /tech/challenge
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - devnet-network

networks:
  devnet-network:
    driver: bridge

volumes:
  postgres_data:
