version: '3.9'

services:
  devnet-postgres:
    container_name: devnet-postgres
    image: postgres:16beta3-alpine3.18
    ports:
      - "5632:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techchallenge
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    networks:
      - rede-devnet

  devnet:
    container_name: devnet
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    env_file: ./.env
    restart: always
    networks:
      - rede-devnet
    depends_on:
      - devnet-postgres
    volumes:
      - armazem:/app/armazem

volumes:
  pg-data:
    name: pg-data
  armazem:
    name: armazem

networks:
  rede-devnet:
    name: rede-devnet
    driver: bridge
