apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devnet-postgres
spec:
  volumeName: pv-devnet-postgres
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi