apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgresdev
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: postgresdev
  template: 
    metadata: 
      labels: 
        app: postgresdev
    spec: 
      containers:
        - name: postgresdev
          image: postgres:16beta3-alpine
          ports: 
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-devnet
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-devnet
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: pvc-devnet-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgresdev
spec:
  ports: 
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresdev
  type: ClusterIP

