apiVersion: v1
kind: Service
metadata: 
  name: devnet-app
spec:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  ports: 
    - port: 9001
      protocol: TCP
      targetPort: 9001
  selector: 
    app: devnet-app

