version: '3.9'

services:
  db:
    image: postgres
    container_name: postgresql_metabase
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRESQL_DB: techchallenge
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_ROOT_HOST: '%'
      POSTGRESQL_TCP_PORT: 5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      -  devnet-network

  devnet-0.0.1-snapshot:
    image: 957817/devnet-0.0.1-snapshot
    restart: always
    build: ./devnet
    working_dir: /devnet
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/techchallenge?serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      -  devnet-network

networks:
  devnet-network:
    driver: bridge

volumes:
  db_data:

