version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=techchallenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - rede-internet
    volumes:
      - pg-data:/var/lib/postgresql/data
  devnet:
    image: devnet:0.0.1
    restart: always
    container_name: devnet
    build:
      context: ./devnet
      dockerfile: Dockerfile
    working_dir: /devnet
    environment:
      TZ: UTC
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: techchallenge
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/techchallenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - 8080:8080
    expose:
      - 8080
    command: mvn spring-boot:run
    depends_on:
      - db
    volumes:
      - armazem:/app/armazem
    networks:
      - rede-internet

volumes:
  pg-data:
  armazem:

networks:
  rede-internet:
    driver: bridge
